
services:
  
  consul-server:
    image: hashicorp/consul:1.21.4
    command: agent -server -bootstrap-expect=1 -client=0.0.0.0 -ui
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - app-network
  control-plane:
    build:
      context: ./control-plane
      dockerfile: Dockerfile
    container_name: control-plane
    environment:
      - CONSUL_URL=consul-server:8500
    networks:
      - app-network
    ports:
      - "10001:18000"
    depends_on:
      consul-server:
        condition: service_started 
  envoy-ingress:
    image: envoyproxy/envoy:v1.33-latest
    volumes:
      - ./envoy.yml:/etc/envoy/envoy.yaml
      - ./certs/ca.crt:/etc/envoy/certs/ca.crt
    ports:
      - "8080:10000"
      - "9901:9901"
    command: sh -c "sleep 10 && envoy -c /etc/envoy/envoy.yaml"
    depends_on:
      consul-agent:
        condition: service_started
      control-plane:
        condition: service_started 
    networks:
      - app-network
  consul-agent:
    image: hashicorp/consul:1.21.4
    command: agent -config-dir=/consul/config
    volumes:
      - ./consul-agent-config:/consul/config
    environment:
      - CONSUL_LOG_LEVEL=debug
    ports:
      - "8502:8502"
    networks:
      - app-network
    depends_on:
      consul-server:
        condition: service_healthy

  streamgate:
    build:
      context: ./streamgate_rs
      dockerfile: Dockerfile
    container_name: fun_taxi-streamgate
    volumes:
      - ./certs/streamgate-server.crt:/streamgate-server.crt
      - ./certs/streamgate-server.key:/streamgate-server.key
    ports:
      - "7067:7067"
    environment:
      - SERVER_IP_ADDRESS=0.0.0.0
      - SERVER_PORT=7067
      - APP_ENV=compose
    networks:
      - app-network
    depends_on:
      consul-server:
        condition: service_healthy
      redis:
        condition: service_started
  streamgate2:
    build:
      context: ./streamgate_rs
      dockerfile: Dockerfile
    container_name: fun_taxi-streamgate2
    volumes:
      - ./certs/streamgate-server.crt:/streamgate-server.crt
      - ./certs/streamgate-server.key:/streamgate-server.key
    ports:
        - "7068:7067"
    environment:
      - SERVER_IP_ADDRESS=0.0.0.0
      - SERVER_PORT=7067
      - APP_ENV=compose
    networks:
      - app-network
    depends_on:
      consul-server:
        condition: service_healthy
      redis:
        condition: service_started

  driver_service:
    build:
      context: ./driver_service_rs
      dockerfile: Dockerfile
    container_name: fun_taxi-driver_service
    ports:
      - "7077:7077"
    networks:
      - app-network
    environment:
      - SERVER_IP_ADDRESS=0.0.0.0
      - SERVER_PORT=7077
      - GEO_SERVICE_GRPC_ADDRESS=http://geo_service:7777
      - STREAMGATE_GRPC_ADDRESS=http://envoy-ingress:10000
      - RABBIT_MQ=amqp://rabbitmq:5672
      - RUST_LOG=debug
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    
  geo_service:
    build:
      context: ./geo_service_rs
      dockerfile: Dockerfile
    container_name: fun_taxi-geo_service
    ports:
     - "8082:8080"
     - "7777:7777"
    networks:
      - app-network
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      schema-registry:
        condition: service_started
    environment:
      - SERVER_IP_ADDRESS=0.0.0.0
      - SERVER_PORT=7077
      - GRPC_SERVER_ADDRESS=0.0.0.0:7777
      - OPEN_SERVICE_API_BASE_URL=https://api.openrouteservice.org/v2
      - OPEN_ROUTES_SERVICE_API_KEY=UNSET
      - REDIS_ADDRESS=redis://redis:6379
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - KAFKA_BROKERS=kafka:9092
      - RABBIT_MQ=amqp://rabbitmq:5672
      - RUST_LOG=debug
  gps_service:
    build:
      context: ./gps_service
      dockerfile: Dockerfile
    container_name: fun_taxi-gps_service
    ports:
     - "8070:8044"
    networks:
      - app-network
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_started
    environment:
      - ASPNETCORE_URLS=http://+:8044
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=true
      - DOTNET_USE_RUNNING_IN_CONTAINER=true
  passenger_service:
    build:
      context: ./passenger_service/passenger_service_app
      dockerfile: Dockerfile
    container_name: fun_taxi-passenger_service
    ports:
     - "8071:8045"
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8045
      - ASPNETCORE_ENVIRONMENT=Compose
      - DOTNET_USE_RUNNING_IN_CONTAINER=true

  # it consumes shared redis in dev
  trip_coordinator_service:
    build:
      context: ./trip_coordinator_service/trip_coordinator_service_app
      dockerfile: Dockerfile
    container_name: fun_taxi-trip_coordinator_service
    ports:
     - "8072:8046"
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - ASPNETCORE_URLS=http://+:8046
      - ASPNETCORE_ENVIRONMENT=Compose
      - DOTNET_USE_RUNNING_IN_CONTAINER=true

  redis:
    image: redis:8.0.3-alpine
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    configs:
      - source: redis-config
        target: /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - app-network

  kafka:
    image: bitnami/kafka:latest
    container_name: fun_taxi-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "bash", "-c", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        micronaut:
          server:
            port: 8083
        akhq:
          connections:
            kafka-cluster:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - "8083:8083"
    networks:
      - app-network
    depends_on:
      kafka:
        condition: service_healthy
    
  schema-registry:
    container_name: schema-registry 
    image: confluentinc/cp-schema-registry:latest
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 5000
    networks:
      - app-network    
    depends_on:
      kafka:
        condition: service_healthy
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"    
    depends_on:
      - passenger_service
    networks:
      - app-network
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network
  redisinsight:
    image: redis/redisinsight
    ports:
      - "8001:5540"
    depends_on:
      - redis
    networks:
      - app-network

  # tile_proxy:
  #   build: 
  #     context: ./map_cache
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8087:8082"
  # user_service:
  #   container_name: user_service
  #   build:
  #     context: ./user_service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8088:80"
  # db:
  #   image: pgrouting/pgrouting:16-3.4-3.6.1
  #   container_name: postgis-db
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: map_db
  #   ports:
  #     - "5444:5432"              
  #   volumes:
  #     - postgis-data:/var/lib/postgresql/data  
  #   restart: always
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    # volumes:
    #   - rabbitmq-lib:/var/lib/rabbitmq/
    #   - rabbitmq-log:/var/log/rabbitmq
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."
  redis-config:
    file: ./redis.conf
volumes:
  grafana_data:
  prometheus_data:
  passenger_sqlite_data:
  kafka-data:
    driver: local
  redis-data:
  postgis-data:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
  consul-data:
networks:
  app-network:
    driver: bridge

  
# # bot_service:
#   #   build:
#   #     context: ./bot_service_rs
#   #     dockerfile: Dockerfile
#   #   container_name: fun_taxi-bot_service
#   #   depends_on:
#   #     - driver_service
#   #     - geo_service
#   #   dns:
#   #     - 8.8.8.8
#   #     - 1.1.1.1