apiVersion: v1
kind: Service
metadata:
  name: fun-taxi-user-service
spec:
  selector:
    app: fun-taxi-user-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
  type: NodePort