apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fun-taxi-kafka
  labels:
    app: fun-taxi-kafka
spec:
  serviceName: fun-taxi-kafka
  replicas: 1
  selector:
    matchLabels:
      app: fun-taxi-kafka
  template:
    metadata:
      labels:
        app: fun-taxi-kafka
    spec:
      containers:
        - name: fun-taxi-kafka
          image: bitnami/kafka:3.7.0
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@fun-taxi-kafka-0.fun-taxi-kafka.default.svc.cluster.local:9093"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://fun-taxi-kafka-0.fun-taxi-kafka.default.svc.cluster.local:9092"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 20
            periodSeconds: 10