# Generated by Django 5.1 on 2024-09-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelloWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('driver_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('start_point', models.JSONField()),
                ('end_point', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
