<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.31.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MassTransit" Version="8.5.1" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.7" />
    <PackageReference Include="NRedisStack" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="proto\trips\v1\trip.proto" GrpcServices="Client" />
    <Protobuf
      Include="proto\trips\v1\trip_state_events\passenger_trip_requested.proto"
      GrpcServices="Client"
    />
    <Protobuf
      Include="proto\trips\v1\trip_state_commands\trip_geoposition_add.proto"
      GrpcServices="Client"
    />
    <Protobuf
      Include="proto\trips\v1\trip_state_commands\trip_geoposition_remove.proto"
      GrpcServices="Client"
    />
    <Protobuf
      Include="proto\trips\v1\trip_state_events\trip_cancellation_requested.proto"
      GrpcServices="Client"
    />
    <Protobuf
      Include="proto\trips\v1\trip_state_events\driver_trip_accepted.proto"
      GrpcServices="Client"
    />
    <Protobuf
      Include="proto\trips\v1\trip_state_events\trip_completion_requested.proto"
      GrpcServices="Client"
    />
    <Protobuf
      Include="proto\trips\v1\trip_state_events\trip_cancelled_by_user.proto"
      GrpcServices="Client"
    />
    <Protobuf
      Include="proto\trips\v1\trip_state_events\trip_assigned_to_driver.proto"
      GrpcServices="Client"
    />
  </ItemGroup>
</Project>
