[package]
name = "bot_service_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde =  { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
tokio-tungstenite = "*"
futures-util = "0.3.31"
tokio-util = "0.7.15"
dotenv = "0.15"
config = "0.15.13"
chrono = {version = "0.4.41",features = ["serde"]}
