apiVersion: v1
kind: Secret
metadata:
  name: fun-taxi-driver-service-secrets
type: Opaque
data:
  Secret_Key: U2VydmVyPW15LXNlcnZlcjtEYXRhYmFzZT1teS1kYjtVc2VyPW15LXVzZXI7UGFzc3dvcmQ9bXktcGFzc3dvcmQ=
